### PR TITLE
orca single point fix

### PR DESCRIPTION
**Pull request by Tetracarbonylnickel**

### CODE REVIEW

**Review by PythonFZ — APPROVED** [review]
I did not encounter this issue - is this related to the new ASE release? (see https://github.com/zincware/IPSuite/issues/312)

**Comment by Tetracarbonylnickel** [comment]
To be honest I don't know. Never used the orca calc before. I just followed the ASE documentation. Did not encountered CP2k issues with the same env, but i will run cp2k calcs soon, verify that, and let you know.

**Comment by M-R-Schaefer** [comment]
Yes I think that's a consequence of the new ASE release

**Comment by Tetracarbonylnickel** [comment]
Should we address the other ASE test fails here or merge and address it in an other PR?

**Comment by M-R-Schaefer** [comment]
huh that's strange. I would suggest to fix the merge conflict and let the tests run again.

**Comment by M-R-Schaefer** [comment]
Something is fishy with the EMT calculator. Exchanging it with the LJ calculator works. I am not super happy with skipping the test (which was done on main) as ase geoopt is pretty essential

**Pull request merged**
